# Smart contract testing
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.12.0

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm install -g truffle@4.1.14
          - npm install -g ganache-cli@6.1.8
          - mv app-config.env.example app-config.env
          #- ganache-cli --port=7545 --blockTime=1 2>&1 > ganache-output.log &
          - ganache-cli --port=7545 --defaultBalanceEther="100000000000000000" 2>&1 > ganache-output.log &
          - truffle test --network=development